package com.tuoming.lteanalysis.GridMatrix.beans;

public class GridInfo {
	public String	DATE;
	public String PROVINCE;
	public String	CITY;
	public long	GRID_ID;
	public float	LON;
	public float	LAT;
	public int	MRNUM;
	public int	MRPOORNUM;
	public float	AVGRSRP;
	public int	CELLSNUM;
	public int	POORCELLSNUM;
	public int	NEIGRIDNUM;
	public int	NEIMRNUM;
	public int	NEIMRPOORNUM;
	public float	NEIAVGRSRP;
	public int	NEICELLSNUM;
	public int	NEIPOORCELLSNUM;
	public long	TOP1ECI;
	public int	TOP1MRNUM;
	public int	TOP1MRPOORNUM;
	public float	TOP1AVGRSRP;
	public int	TOP1NEIGRID;
	public int	TOP1ANGLE;
	public float	TOP1DIS;
	public long	TOP2ECI;
	public int	TOP2MRNUM;
	public int	TOP2MRPOORNUM;
	public float	TOP2AVGRSRP;
	public int	TOP2NEIGRID;
	public int	TOP2ANGLE;
	public float	TOP2DIS;
	public long	TOP3ECI;
	public int	TOP3MRNUM;
	public int	TOP3MRPOORNUM;
	public float	TOP3AVGRSRP;
	public int	TOP3NEIGRID;
	public int	TOP3ANGLE;
	public float	TOP3DIS;
	public long	TOPECIALLNUMECI;
	public int	TOPECIALLNUM;
	public int	TOPECIPOORNUM;
	public float	TOPECIAVGRSRP;
	public int	TOPECIANGLE;
	public float	TOPECIDIS;
}
