package com.tuoming.lteanalysis.GridMatrix.beans;

public class MrsStatRsrp {
	public String	date;
	public long	ECI;
	public int mr_rsrp[] = new int[48];
//	public int	mr_rsrp_00;
//	public int	mr_rsrp_01;
//	public int	mr_rsrp_02;
//	public int	mr_rsrp_03;
//	public int	mr_rsrp_04;
//	public int	mr_rsrp_05;
//	public int	mr_rsrp_06;
//	public int	mr_rsrp_07;
//	public int	mr_rsrp_08;
//	public int	mr_rsrp_09;
//	public int	mr_rsrp_10;
//	public int	mr_rsrp_11;
//	public int	mr_rsrp_12;
//	public int	mr_rsrp_13;
//	public int	mr_rsrp_14;
//	public int	mr_rsrp_15;
//	public int	mr_rsrp_16;
//	public int	mr_rsrp_17;
//	public int	mr_rsrp_18;
//	public int	mr_rsrp_19;
//	public int	mr_rsrp_20;
//	public int	mr_rsrp_21;
//	public int	mr_rsrp_22;
//	public int	mr_rsrp_23;
//	public int	mr_rsrp_24;
//	public int	mr_rsrp_25;
//	public int	mr_rsrp_26;
//	public int	mr_rsrp_27;
//	public int	mr_rsrp_28;
//	public int	mr_rsrp_29;
//	public int	mr_rsrp_30;
//	public int	mr_rsrp_31;
//	public int	mr_rsrp_32;
//	public int	mr_rsrp_33;
//	public int	mr_rsrp_34;
//	public int	mr_rsrp_35;
//	public int	mr_rsrp_36;
//	public int	mr_rsrp_37;
//	public int	mr_rsrp_38;
//	public int	mr_rsrp_39;
//	public int	mr_rsrp_40;
//	public int	mr_rsrp_41;
//	public int	mr_rsrp_42;
//	public int	mr_rsrp_43;
//	public int	mr_rsrp_44;
//	public int	mr_rsrp_45;
//	public int	mr_rsrp_46;
//	public int	mr_rsrp_47;
	public int	reportnum;
	public int sum_mr_rsrp;

}
